begin;

create table if not exists public.simulador_saude_cotacoes (
  id uuid primary key default gen_random_uuid(),
  codigo bigint generated by default as identity unique,
  cliente_nome text not null default '',
  cliente_cnpj text,
  cliente_cidade text,
  tipo_contratacao text not null default 'Empresarial (PJ)',
  vigencia date,
  status text not null default 'rascunho',
  snapshot_version integer not null default 1,
  snapshot jsonb not null default '{}'::jsonb,
  created_by uuid not null default public.app_usuario_atual_id() references public.usuarios(id) on delete restrict,
  updated_by uuid references public.usuarios(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint simulador_saude_cotacoes_status_check check (status in ('rascunho', 'proposta', 'arquivada')),
  constraint simulador_saude_cotacoes_snapshot_object_check check (jsonb_typeof(snapshot) = 'object')
);

create index if not exists simulador_saude_cotacoes_owner_updated_idx
  on public.simulador_saude_cotacoes (created_by, updated_at desc);

comment on table public.simulador_saude_cotacoes is
  'Cotação versionada como snapshot imutável de preços e dados de plano para preservar o histórico comercial.';
comment on column public.simulador_saude_cotacoes.snapshot is
  'Snapshot do cliente, vidas, agrupamentos, planos selecionados e preços por faixa no momento do salvamento.';

create or replace function private.simulador_saude_preparar_cotacao()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if tg_op = 'INSERT' then
    new.created_by := public.app_usuario_atual_id();
    new.updated_by := public.app_usuario_atual_id();
    new.created_at := now();
  else
    new.created_by := old.created_by;
    new.created_at := old.created_at;
    new.updated_by := public.app_usuario_atual_id();
  end if;
  new.updated_at := now();
  return new;
end;
$$;

revoke all on function private.simulador_saude_preparar_cotacao() from public, anon, authenticated;
drop trigger if exists simulador_saude_cotacoes_prepare on public.simulador_saude_cotacoes;
create trigger simulador_saude_cotacoes_prepare
before insert or update on public.simulador_saude_cotacoes
for each row execute function private.simulador_saude_preparar_cotacao();

create table if not exists public.simulador_saude_cotacao_versoes (
  id uuid primary key default gen_random_uuid(),
  cotacao_id uuid not null references public.simulador_saude_cotacoes(id) on delete restrict,
  versao integer not null,
  snapshot jsonb not null,
  usuario_id uuid references public.usuarios(id) on delete set null,
  created_at timestamptz not null default now(),
  constraint simulador_saude_cotacao_versoes_numero_key unique (cotacao_id, versao),
  constraint simulador_saude_cotacao_versoes_snapshot_object_check check (jsonb_typeof(snapshot) = 'object')
);

create index if not exists simulador_saude_cotacao_versoes_cotacao_created_idx
  on public.simulador_saude_cotacao_versoes (cotacao_id, created_at desc);

create or replace function private.simulador_saude_versionar_cotacao()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if tg_op = 'INSERT' then
    new.snapshot_version := 1;
  elsif new.cliente_nome is distinct from old.cliente_nome
     or new.cliente_cnpj is distinct from old.cliente_cnpj
     or new.cliente_cidade is distinct from old.cliente_cidade
     or new.tipo_contratacao is distinct from old.tipo_contratacao
     or new.vigencia is distinct from old.vigencia
     or new.status is distinct from old.status
     or new.snapshot is distinct from old.snapshot then
    new.snapshot_version := old.snapshot_version + 1;
  else
    new.snapshot_version := old.snapshot_version;
  end if;

  return new;
end;
$$;

create or replace function private.simulador_saude_gravar_versao_cotacao()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_alterada boolean := true;
begin
  if tg_op = 'UPDATE' then
    v_alterada := new.snapshot_version is distinct from old.snapshot_version;
  end if;
  if v_alterada then
    insert into public.simulador_saude_cotacao_versoes (cotacao_id, versao, snapshot, usuario_id)
    values (new.id, new.snapshot_version, new.snapshot, public.app_usuario_atual_id());
  end if;
  return new;
end;
$$;

revoke all on function private.simulador_saude_versionar_cotacao() from public, anon, authenticated;
revoke all on function private.simulador_saude_gravar_versao_cotacao() from public, anon, authenticated;
drop trigger if exists simulador_saude_cotacoes_snapshot_before on public.simulador_saude_cotacoes;
create trigger simulador_saude_cotacoes_snapshot_before
before insert or update on public.simulador_saude_cotacoes
for each row execute function private.simulador_saude_versionar_cotacao();
drop trigger if exists simulador_saude_cotacoes_snapshot_after on public.simulador_saude_cotacoes;
create trigger simulador_saude_cotacoes_snapshot_after
after insert or update on public.simulador_saude_cotacoes
for each row execute function private.simulador_saude_gravar_versao_cotacao();

alter table public.simulador_saude_cotacoes enable row level security;
revoke all on table public.simulador_saude_cotacoes from anon, authenticated;
grant select, insert, update on table public.simulador_saude_cotacoes to authenticated;
alter table public.simulador_saude_cotacao_versoes enable row level security;
revoke all on table public.simulador_saude_cotacao_versoes from anon, authenticated;
grant select on table public.simulador_saude_cotacao_versoes to authenticated;

drop policy if exists simulador_saude_cotacoes_select on public.simulador_saude_cotacoes;
create policy simulador_saude_cotacoes_select on public.simulador_saude_cotacoes
  for select to authenticated
  using (
    (select public.app_tem_permissao('simulador_saude', 'view'))
    and (
      created_by = (select public.app_usuario_atual_id())
      or (select public.app_tem_permissao('simulador_saude', 'view_all'))
    )
  );

drop policy if exists simulador_saude_cotacoes_insert on public.simulador_saude_cotacoes;
create policy simulador_saude_cotacoes_insert on public.simulador_saude_cotacoes
  for insert to authenticated
  with check (
    (select public.app_tem_permissao('simulador_saude', 'create'))
    and created_by = (select public.app_usuario_atual_id())
  );

drop policy if exists simulador_saude_cotacoes_update on public.simulador_saude_cotacoes;
create policy simulador_saude_cotacoes_update on public.simulador_saude_cotacoes
  for update to authenticated
  using (
    (select public.app_tem_permissao('simulador_saude', 'update'))
    and created_by = (select public.app_usuario_atual_id())
  )
  with check (
    (select public.app_tem_permissao('simulador_saude', 'update'))
    and created_by = (select public.app_usuario_atual_id())
  );

drop policy if exists simulador_saude_cotacao_versoes_select on public.simulador_saude_cotacao_versoes;
create policy simulador_saude_cotacao_versoes_select on public.simulador_saude_cotacao_versoes
  for select to authenticated
  using (
    (select public.app_tem_permissao('simulador_saude', 'view'))
    and exists (
      select 1 from public.simulador_saude_cotacoes cotacao
      where cotacao.id = cotacao_id
        and cotacao.created_by = (select public.app_usuario_atual_id())
    )
  );

create or replace function public.simulador_saude_dados_corretora()
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_dados jsonb;
begin
  if not public.app_tem_permissao('simulador_saude', 'view') then
    raise exception 'Acesso não autorizado.' using errcode = '42501';
  end if;

  select jsonb_build_object(
    'razao_social', config.razao_social,
    'nome_fantasia', config.nome_fantasia,
    'cnpj', config.cnpj,
    'inscricao_estadual', config.inscricao_estadual,
    'susep', config.susep,
    'email', config.email,
    'telefone', config.telefone,
    'whatsapp', config.whatsapp,
    'site', config.site,
    'endereco_logradouro', config.endereco_logradouro,
    'endereco_numero', config.endereco_numero,
    'endereco_complemento', config.endereco_complemento,
    'endereco_bairro', config.endereco_bairro,
    'endereco_cidade', config.endereco_cidade,
    'endereco_uf', config.endereco_uf,
    'endereco_cep', config.endereco_cep,
    'logo_url', config.logo_url
  )
  into v_dados
  from public.corretora_configuracoes config
  where config.status = 'ativo'
  order by config.updated_at desc nulls last, config.created_at desc nulls last
  limit 1;

  return coalesce(v_dados, '{}'::jsonb);
end;
$$;

revoke all on function public.simulador_saude_dados_corretora() from public, anon;
grant execute on function public.simulador_saude_dados_corretora() to authenticated;

commit;
