-- Restringe a gravação das configurações aos submódulos gerenciados pela Home.
-- Evita que uma chamada direta à API altere outros recursos de acesso.
drop policy if exists recursos_acesso_update_admin_module_settings
  on public.recursos_acesso;

create policy recursos_acesso_update_admin_module_settings
  on public.recursos_acesso
  for update to authenticated
  using (
    tipo = 'aba'
    and chave = any (array[
      'painel_ar.inicio',
      'painel_ar.gerar_links',
      'painel_ar.crm_2',
      'painel_ar.crm2.cadastro_pf',
      'painel_ar.crm2.cadastro_pj',
      'painel_ar.crm2.vinculos',
      'painel_ar.crm2.pedidos',
      'painel_ar.crm2.oportunidades',
      'painel_ar.crm2.comunicacao',
      'painel_ar.crm2.automacoes',
      'painel_ar.produtos',
      'painel_ar.validacoes',
      'painel_ar.historico',
      'painel_ar.crm',
      'central_senhas.acessos',
      'central_senhas.links',
      'central_senhas.links_corretora',
      'central_senhas.links_ar',
      'central_senhas.links_gestao',
      'financeiro.dashboard',
      'financeiro.lancamentos',
      'home.financeiro.lancamentos.titulos',
      'home.financeiro.lancamentos.receber',
      'home.financeiro.lancamentos.pagar',
      'home.financeiro.lancamentos.parcelas',
      'home.financeiro.lancamentos.recorrentes',
      'home.financeiro.lancamentos.rateios',
      'home.financeiro.lancamentos.baixas',
      'financeiro.conciliacao',
      'financeiro.cartoes',
      'financeiro.relatorios',
      'financeiro.cadastros',
      'home.financeiro.cadastros.pessoas',
      'home.financeiro.cadastros.contas',
      'home.financeiro.cadastros.categorias',
      'home.financeiro.cadastros.centros_custo',
      'home.financeiro.cadastros.linhas_negocio',
      'home.financeiro.cadastros.contratos',
      'financeiro.configuracoes',
      'home.financeiro.configuracoes.parametros',
      'home.financeiro.configuracoes.alertas',
      'home.financeiro.configuracoes.backups',
      'home.financeiro.configuracoes.auditoria',
      'home.financeiro.configuracoes.homologacao',
      'rh_dp.dashboard',
      'rh_dp.colaboradores',
      'rh_dp.demandas_contabilidade',
      'rh_dp.fechamentos',
      'admin.sistema.corretora',
      'admin.logs_integracoes',
      'admin.limites',
      'admin.categorias',
      'admin.grupos',
      'admin.usuarios',
      'admin.perfis',
      'admin.parceiros_indicacao'
    ]::text[])
    and public.app_tem_permissao('admin.modulos', 'update')
  )
  with check (
    tipo = 'aba'
    and chave = any (array[
      'painel_ar.inicio',
      'painel_ar.gerar_links',
      'painel_ar.crm_2',
      'painel_ar.crm2.cadastro_pf',
      'painel_ar.crm2.cadastro_pj',
      'painel_ar.crm2.vinculos',
      'painel_ar.crm2.pedidos',
      'painel_ar.crm2.oportunidades',
      'painel_ar.crm2.comunicacao',
      'painel_ar.crm2.automacoes',
      'painel_ar.produtos',
      'painel_ar.validacoes',
      'painel_ar.historico',
      'painel_ar.crm',
      'central_senhas.acessos',
      'central_senhas.links',
      'central_senhas.links_corretora',
      'central_senhas.links_ar',
      'central_senhas.links_gestao',
      'financeiro.dashboard',
      'financeiro.lancamentos',
      'home.financeiro.lancamentos.titulos',
      'home.financeiro.lancamentos.receber',
      'home.financeiro.lancamentos.pagar',
      'home.financeiro.lancamentos.parcelas',
      'home.financeiro.lancamentos.recorrentes',
      'home.financeiro.lancamentos.rateios',
      'home.financeiro.lancamentos.baixas',
      'financeiro.conciliacao',
      'financeiro.cartoes',
      'financeiro.relatorios',
      'financeiro.cadastros',
      'home.financeiro.cadastros.pessoas',
      'home.financeiro.cadastros.contas',
      'home.financeiro.cadastros.categorias',
      'home.financeiro.cadastros.centros_custo',
      'home.financeiro.cadastros.linhas_negocio',
      'home.financeiro.cadastros.contratos',
      'financeiro.configuracoes',
      'home.financeiro.configuracoes.parametros',
      'home.financeiro.configuracoes.alertas',
      'home.financeiro.configuracoes.backups',
      'home.financeiro.configuracoes.auditoria',
      'home.financeiro.configuracoes.homologacao',
      'rh_dp.dashboard',
      'rh_dp.colaboradores',
      'rh_dp.demandas_contabilidade',
      'rh_dp.fechamentos',
      'admin.sistema.corretora',
      'admin.logs_integracoes',
      'admin.limites',
      'admin.categorias',
      'admin.grupos',
      'admin.usuarios',
      'admin.perfis',
      'admin.parceiros_indicacao'
    ]::text[])
    and public.app_tem_permissao('admin.modulos', 'update')
  );
